spring:
  application:
    name: Turf Novo
  datasource:
    url: jdbc:postgresql://turf-novo-prod.postgres.database.azure.com/turf_novo
    username: turf_novo_user
    password: '${ secrets.TURF_NOVO_USER_PASSWORD }'
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        ddl-auto: create-drop
    generate-ddl: true
turfnovo:
  app:
    jwtSecret: '${ secrets.TURF_NOVO_JWT_SECRET }'
